/* TARGET=bcm6348-dmt-T1-dmtbis-adsl2plus-L2-SRA-firmware-DslOs-Qproc-HW-RTL-pipeline-IncOneBit-Readsl2-doubleUS-IM24k  */

#define SOURCE_FILE_ 
#define BCM6348_SRC 
#define G994_T1P413_1024_FFT 
#define XY_NOISE_MONITORING 
#define ENABLE_DIG_USPWR_CUTBACK 
#define ADSLCORE_ONLY 
#define PLN_MEASUREMENT_ENABLED 
#define CCOMB_POWER_DETECTION 
#define EXT_INP_SUPPORT 
#define D_MULTIPLE_OF_32 
#define DISTORTION_TEST 
#define TEQ_DF 
#define LOOP_TIMING_PLL 
#define RCV_PHASE_TWEAK_ONLY 
#define ADSL_MAX_POSSIBLE_RCV_RATE 
#define HARDWARE_CHANNEL 
#define ADSL_HARDWARE_AGC 
#define HW_CHANNEL_ADC 
#define HW_CHANNEL_DAC 
#define HW_PGA 
#define DIGITALEC_SINGLE_TAP_UPDATE 
#define ANALOGEC_SINGLE_TAP_UPDATE 
#define HWLOG 
#define G992_TRELLIS_CODE_CLAMPING 
#define G992DECODERTRELLISBOUNDARY 
#define MEMORYLIMIT64K 
#define bcm47xx 
#define DSL_BIG_ENDIAN 
#define MIPS_SRC 
#define VP_INLINE -Winline 
#define GLOBAL_PTR_BIAS=32768 
#define SLOW_VAR_GLOBAL_REG 
#define USE_ASM_API 
#define RTL_SRC 
#define RSENC_INLINE 
#define BITENC_INLINE 
#define USE_SLOW_DATA 
#define USE_FAST_TEXT 
#define PROFILE_INLINE 
#define CHIP_SRC 
#define G992_RESYNC_PILOT_PHASE_IN_SHOWTIME 
#define DSL_OS 
#define G992_FEQ_UPDATE_IN_SYNCH_SYMBOL 
#define G992_APPLY_SSVI 
#define SHARE_TEQ_VARS 
#define G994P1_SUPPORT_A43C 
#define ANNEX_M 
#define DOUBLE_UP_STREAM 
#define EXTENDED_INTERLEAVE_DEPTH_24K 
#define G992_ENABLE_TRAINING_PLN 
#define USE_ASM_API 
#define MIPS_ASM 
#define G992P3_ENABLE_FULLBAND_BITSWAP 
#define CPE_IDEAL_MEDLEY 
#define G992_LOS_HANDLING_ESCAPE 
#define MEMORYLIMIT64K 
#define ADSL_FIRMWARE 
#define G992DATA_XMT_COMPACT_WORD 
#define ADSL_MAX_POSSIBLE_RCV_RATE 
#define DSP_FRONTEND_ONLY 
#define G992P3_ONE_BIT_CONSTELLATION 
#define G992P3_ONE_BIT_CONSTELLATION_DS 
#define ADSL_MODEM 
#define ATM 
#define ADSL_ATUR 
#define ADSL_SOFTWARE_TIME_ERROR_CALCULATION 
#define DSL_REPORT_ALL_COUNTERS 
#define ADSL_MONITOR_LCD 
#define G994P1 
#define G994P1_ATUR 
#define G992 
#define G992_ATUR 
#define ADSL_FRAMER 
#define G997_1 
#define ATM_I432 
#define PLN_MEASUREMENT_ENABLED 
#define TEQ_DF 
#define G992_ATUR_UPSTREAM_SAMPLING_FREQ_276KHZ 
#define G994P1_ATUR_UPSTREAM_SAMPLING_FREQ_276KHZ 
#define G992_TRELLISCODE 
#define ADSL_HARDWARE_ECHO_CANCELLOR 
#define G992P1 
#define G992P1_ATUR 
#define G992P1_ANNEX_A 
#define ADSL_HARDWARE_TIME_ERROR_TRACKING 
#define G992P1_NEWFRAME 
#define G992P1_NEWFRAME_ATUR 
#define G992P1_ANNEX_A_USED_FOR_G992P2 
#define SPECIAL_FIX_KT 
#define T1P413 
#define G992_ATUR_UPSTREAM_SAMPLING_FREQ_276KHZ 
#define G992_CALC_DEBUG_SNR_BEFORE_TEQ 
#define G992P3 
#define RATE_SELECT_E14 
#define G992P3_ATUR 
#define G992P3AMENDMENT 
#define GLOBESPAN_DM 
#define G992P3_COMB_MSG_THREE_COPIES 
#define G992P3_POWER_MANAGEMENT 
#define G992P3_SRA 
#define G992P5 
#define G992P5_ATUR 
#define ADSL_PIPELINE_CODE 
#define ADSL_HARDWARE_TIME_ERROR_TRACKING 
#define G994P1RCV_QPROC 
#define G994P1XMT_QPROC 
#define G992RCV_QPROC 
#define G992XMT_QPROC 
#define G992RCV_RS 
#define VP_SIMULATOR 
#define T1P413RCV_QPROC 
#define T1P413XMT_QPROC 
#define G992ENC_HW_DATAMODE 
#define G992DATA_XMT_HW_RS 
#define G992DATA_XMT_COMPACT_WORD 
#define USE_RANDOM_NUMBER_FOR_ECHO_CANCELLER_TRAINING 
#define G992RCV_QPROC_FAST 
#define G992_BIT_SWAP 
#define ADSL_IDENTIFY_VENDOR_FIRMWARE 
#define ADSL_ATUR_FORCE_BIGGER_UPSTREAM_MARGIN 
#define G992_MORE_FRAME_MODE 
#define XMT_RACT2_FOR_ADI_COMPATIBILITY 
#define XMT_FFT_SIZE_2X 
#define SYNCH_SYMBOL_DETECTION 
#define ANSI_CACT12_PING_PONG 
#define ADSL_SPECIAL_FIX_FOR_FRENCH_TELECOM 
#define G994P1_CHECK_SECURITY 
#define G994P1_NON_STD_INFO 
#define I432_HEADER_COMPRESSION 
#define TDC_IOP_FIX_ERICSSON_TI_4000C_350 
#define TDC_IOP_FIX_SEIMENS_TI 
#define FT_ADI_US_RATE_FIX 
#define ANSI_CACT12_PING_PONG 
#define G992_ATUR_UPSTREAM_SAMPLING_FREQ_276KHZ 
#define G994P1_ATUR_UPSTREAM_SAMPLING_FREQ_276KHZ 
#define READSL2 
#define G992_APPLY_SSVI 
#define READSL2_FILTERS


#define ADSL_PHY_XFACE_OFFSET 0x21F90


#define ADSL_PHY_SDRAM_BIAS 0x1A0000


#define ADSL_PHY_SDRAM_LINK_OFFSET 0x1A0000


#define ADSL_PHY_SDRAM_PAGE_SIZE 0x200000
